In [3]:
import numpy as np

In [4]:
x = [[1,2,3], [4,5,6], [7,8,9]]

In [5]:
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
y = np.array(x)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
y.min()

1

In [8]:
y.argmin()

0

In [9]:
y.max()

9

In [10]:
y.argmax()

8

In [11]:
np.zeros((3,2)) +  5   # An matrix of 3 rows, 2 column is created, every element is zero which is incremented then by 5

array([[5., 5.],
       [5., 5.],
       [5., 5.]])

In [12]:
np.ones((3,2))  # you need to use double bracket for 2 D Matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
np.eye(3)   # eye keyword is used for identity matrix. identity matrix is a square matrix which requires only one parameter

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(50).reshape(5, 10)  # we use reshape for defining order of matrix i.e. 5 rows & 10 columns

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [17]:
np.linspace(0, 10, 5)  #linearly spaced

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
np.random.rand(5)  # 5 random values between 0 & 1

array([0.93489024, 0.55281576, 0.63512036, 0.76517273, 0.2593672 ])

In [19]:
np.random.randn(5)  # 5 random (some negative values) 

array([-1.11688712, -0.60365913,  0.15750794, -1.26510691,  0.32549037])

In [20]:
np.random.randint(100) # any random integer value < 100

65

In [21]:
s = np.arange(0, 21)

In [22]:
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [39]:
s.sum()

210

In [40]:
s[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
s[10:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [42]:
s[2:5]

array([2, 3, 4])

In [43]:
t = s.copy()  # copies the array to t

In [44]:
t

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [45]:
u = np.arange(25).reshape(5, 5)
u

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
u[4][2] # Can use u(4,2) as well

22

In [47]:
u[0:2, 2:]  # slicing

array([[2, 3, 4],
       [7, 8, 9]])

In [48]:
# google numpy operations.