In [58]:
import numpy as np

In [59]:
x = [[1,2,3], [4,5,6], [7,8,9]]

In [60]:
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [61]:
y = np.array(x)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
y.min()

1

In [63]:
y.argmin()

0

In [64]:
y.max()

9

In [65]:
y.argmax()

8

In [66]:
np.zeros((3,2)) +  5   # An matrix of 3 rows, 2 column is created, every element is zero which is incremented then by 5

array([[5., 5.],
       [5., 5.],
       [5., 5.]])

In [67]:
np.ones((3,2))  # you need to use double bracket for 2 D Matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [68]:
np.eye(3)   # eye keyword is used for identity matrix. identity matrix is a square matrix which requires only one parameter

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [71]:
np.arange(50).reshape(5, 10)  # we use reshape for defining order of matrix i.e. 5 rows & 10 columns

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [72]:
np.linspace(0, 10, 5)  #linearly spaced

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [73]:
np.random.rand(5)  # 5 random values between 0 & 1

array([0.24051053, 0.91103172, 0.24204873, 0.82272459, 0.73618424])

In [74]:
np.random.randn(5)  # 5 random (some negative values) 

array([-0.70391065, -3.02838688, -0.28574823, -1.3694211 ,  1.0524785 ])

In [75]:
np.random.randint(100) # any random integer value < 100

47